#!/bin/sh
#  --enable-libass \ nincs meg!!
#  --enable-libfreetype  nincs meg !!
#  --enable-libtheora \ nincs meg !!
#  --enable-libvorbis \
#  --enable-libx264 \
#  --enable-libx265 \

cd ./ffmpeg

PATH="$HOME/bin:$PATH" \
PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH" \
./configure \
 --prefix="/usr" \
 --extra-cflags="-I/usr/include" \
 --extra-ldflags="-L/usr/lib -Bsybolic" \
 --bindir="/usr/local/bin" \
 --pkg-config="$PKG_CONFIG_PATH" \
 --enable-shared \
 --enable-gpl \
 --enable-pic \
 --enable-libfdk-aac \
 --enable-libmp3lame \
 --enable-libvpx \
 --enable-nonfree \
 --enable-x11grab \
 --disable-muxer=a64 \
 --disable-encoder=a64multi \
 --disable-encoder=a64multi5
 
PATH="$HOME/bin:$PATH" make
sudo make install
make clean

